### ISSUE TITLE
Origin of animated elements

### ISSUE THREAD

**Issue by rhorbas** [razorjack/quicksand#107]
I am using most of this demo here:
http://razorjack.net/quicksand/demos/one-set-clone.html
but with a left floating filter div as subnavigation, so the container with the filtered elements does not have full page width.
When filtering, the animated elements first wander across the subnavigation before falling into place inside their container div, which looks awkward.

When applying my css to the original example (via Firebug), I get the same effect:

``` css
#filter {
    float: left;
    height: 1000px;
}
#filter input[type="radio"] {
    display: none;
}
#filter label {
    width: 200px;
    background-color: #F5F5F5;
    color: #00AEEF;
    display: block;
    padding: 11px;
}
```

Is there a way to avoid this?
